<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- General Project Settings -->
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Nullable>enable</Nullable>
    <EnableDynamicLoading>true</EnableDynamicLoading>

    <!-- NuGet Package Metadata -->
    <PackageId>LimboConsole.Sharp</PackageId>
    <Version>0.0.1-beta-010</Version>
    <Authors>RcubDev</Authors>
    <Description>A simple c# wrapper for the limbo_console plug-in for godot.
      See https://github.com/limbonaut/limbo_console
    </Description>
    <Copyright>Copyright © 2025 RcubDev</Copyright>
    <PackageTags>godot;limbo;console;</PackageTags>
    <IncludeBuildOutput>true</IncludeBuildOutput>
    <RepositoryUrl>https://github.com/RcubDev/limbo_console_sharp</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/RcubDev/limbo_console_sharp</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <VersionFilePath>$(MSBuildThisFileDirectory)..\version.txt</VersionFilePath>
    <PackageReleaseNotes>See the changelog at
      https://github.com/RcubDev/limbo_console_sharp/blob/main/CHANGELOG.md</PackageReleaseNotes>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
    <None Include="..\CHANGELOG.md" Pack="true" PackagePath="\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="[4.4.0, 5.0.0)" />
  </ItemGroup>
  <Target Name="WriteVersionToFile" AfterTargets="Build">
    <WriteLinesToFile File="$(VersionFilePath)" Lines="$(Version)" Overwrite="true" />
  </Target>
  <ItemGroup>
    <!-- Generator -->
    <None
      Include="..\Limbo.Console.Generator\bin\$(Configuration)\netstandard2.0\Limbo.Console.Generator.dll"
      Pack="true" 
	  PackagePath="analyzers/dotnet/cs/" />
    <!-- Include the attribute's dll in the nuget package so users can utilize it -->
    <None
      Include="..\Limbo.Console.Abstractions\bin\$(Configuration)\netstandard2.0\Limbo.Console.Abstractions.dll"
      Pack="true"
      PackagePath="lib/net8.0/" />
    <!-- Auto-wire the analyzer -->
    <!-- Nuget seemingly has issues / warnings if both versions of this file was not included -->
    <None Include="build\Limbo.Console.Sharp.targets" Pack="true"
      PackagePath="build\Limbo.Console.Sharp.targets" />
    <None Include="build\LimboConsole.Sharp.targets" Pack="true"
      PackagePath="build\LimboConsole.Sharp.targets" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Limbo.Console.Generator\Limbo.Console.Generator.csproj"
      ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>